version: '3.8'

services:
  news-service:
    image: truongikpk/bookstore-news-service:v1.0.0
    container_name: news-service
    ports:
      - "8089:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
