apiVersion: v1
kind: ConfigMap
metadata:
  name: news-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://bookstore-db-do-user-36177370-0.h.db.ondigitalocean.com:25060/bookstore_news?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
